### PR TITLE
Minor refactoring of classes to make tidier.

### PR DESCRIPTION
**Pull request by Patyfatycake**
Fixed OCE Server IP Address

Refactored to make tidier.

### CODE REVIEW

**Comment by mayuso** [comment]
The code is a lot cleaner now, and OCE IP really helps. I will merge as soon as I test it. Thank you.

**Comment by mayuso** [comment]
I tried to compile the code, and got this error:

    Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at main.java.mayuso.LoLPing.Ping.getPing(Ping.java:29)
        at main.java.mayuso.LoLPing.UI.start(UI.java:66)
        at main.java.mayuso.LoLPing.UI.access$0(UI.java:62)
        at main.java.mayuso.LoLPing.UI$1.actionPerformed(UI.java:57)

I don´t have much free time this weekend, I will try to have a look at the code more in detail as soons as possible.

**Comment by mayuso** [comment]
I also realised I need to change the package names, might do that after fixing that Null Pointer Exception and merging.

**Comment by Patyfatycake** [comment]
I guess its something to do with the projects, I am using intellij how about you?

**Comment by mayuso** [comment]
With `I need to change the package names` I meant I need to change `xxx.yyy.mayuso.zzz`, I think it is better to have the project name there, not the creators name.

**Comment by Patyfatycake** [comment]
Would you like me to do that? Or are you fine with it.

**Comment by mayuso** [comment]
I will, that´s 5 minutes of work, I am waiting for this PR to be fixed first (I need some more time for this xD).

**Pull request closed without merging**
